const PATIENTS_FETCH_IS_LOADING = "PATIENTS_FETCH_IS_LOADING";
const PATIENTS_FETCH_SUCCESS = "PATIENTS_FETCH_SUCCESS";
const PATIENTS_FETCH_FAILURE = "PATIENTS_FETCH_FAILURE";

export {
  PATIENTS_FETCH_IS_LOADING,
  PATIENTS_FETCH_SUCCESS,
  PATIENTS_FETCH_FAILURE,
};
